# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task -a

  build:
    cmd: docker build -f docker/Dockerfile -t icsm-prez-ui docker

  run:
    cmd: docker run -p 3000:3000 icsm-prez-ui
