name: Release

on:
  release:
    types:
      - published

jobs:
  build-dev:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: dev
      prez_api_endpoint: https://data-api.dev.qlocation.information.qld.gov.au

  build-uat:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: uat
      prez_api_endpoint: https://data-api.uat.qlocation.information.qld.gov.au

  build-prod:
    uses: ./.github/workflows/build-image.yml
    with:
      environment: prod
      prez_api_endpoint: https://data-api.qlocation.information.qld.gov.au
